//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignMode.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesignMode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 New Action 的本地化字符串。
        /// </summary>
        internal static string ActionDesign {
            get {
                return ResourceManager.GetString("ActionDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new action. 的本地化字符串。
        /// </summary>
        internal static string ActionDesignDesc {
            get {
                return ResourceManager.GetString("ActionDesignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Composite 的本地化字符串。
        /// </summary>
        internal static string CompositeDesign {
            get {
                return ResourceManager.GetString("CompositeDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new sequence, selector or parallel. 的本地化字符串。
        /// </summary>
        internal static string CompositeDesignDesc {
            get {
                return ResourceManager.GetString("CompositeDesignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Condition 的本地化字符串。
        /// </summary>
        internal static string ConditionDesign {
            get {
                return ResourceManager.GetString("ConditionDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new condition. 的本地化字符串。
        /// </summary>
        internal static string ConditionDesignDesc {
            get {
                return ResourceManager.GetString("ConditionDesignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Decorator 的本地化字符串。
        /// </summary>
        internal static string DecoratorDesign {
            get {
                return ResourceManager.GetString("DecoratorDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new decorator. 的本地化字符串。
        /// </summary>
        internal static string DecoratorDesignDesc {
            get {
                return ResourceManager.GetString("DecoratorDesignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label 的本地化字符串。
        /// </summary>
        internal static string DesignLabel {
            get {
                return ResourceManager.GetString("DesignLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The label shown on the node. 的本地化字符串。
        /// </summary>
        internal static string DesignLabelDesc {
            get {
                return ResourceManager.GetString("DesignLabelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Event 的本地化字符串。
        /// </summary>
        internal static string EventDesign {
            get {
                return ResourceManager.GetString("EventDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new event. 的本地化字符串。
        /// </summary>
        internal static string EventDesignDesc {
            get {
                return ResourceManager.GetString("EventDesignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Impulse 的本地化字符串。
        /// </summary>
        internal static string ImpulseDesign {
            get {
                return ResourceManager.GetString("ImpulseDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new impulse. 的本地化字符串。
        /// </summary>
        internal static string ImpulseDesignDesc {
            get {
                return ResourceManager.GetString("ImpulseDesignDesc", resourceCulture);
            }
        }
    }
}
