//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Person.proto
// Note: requires additional types generated from: result.proto
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CPerson")]
  public partial class CPerson : global::ProtoBuf.IExtensible
  {
    public CPerson() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Email = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Email
    {
      get { return _Email; }
      set { _Email = value; }
    }
    private int _Page = (int)10;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)10)]
    public int Page
    {
      get { return _Page; }
      set { _Page = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Samples = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"Samples", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> Samples
    {
      get { return _Samples; }
    }
  
    private Message.CPerson.ECorpus _Corpus = Message.CPerson.ECorpus.WEB;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Corpus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Message.CPerson.ECorpus.WEB)]
    public Message.CPerson.ECorpus Corpus
    {
      get { return _Corpus; }
      set { _Corpus = value; }
    }
    private readonly global::System.Collections.Generic.List<Message.CResult> _Result = new global::System.Collections.Generic.List<Message.CResult>();
    [global::ProtoBuf.ProtoMember(7, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Message.CResult> Result
    {
      get { return _Result; }
    }
  
    private readonly global::System.Collections.Generic.List<Message.CPerson.CInternalClass> _InternalClass = new global::System.Collections.Generic.List<Message.CPerson.CInternalClass>();
    [global::ProtoBuf.ProtoMember(8, Name=@"InternalClass", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Message.CPerson.CInternalClass> InternalClass
    {
      get { return _InternalClass; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInternalClass")]
  public partial class CInternalClass : global::ProtoBuf.IExtensible
  {
    public CInternalClass() {}
    
    private string _url;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _snippets = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"snippets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> snippets
    {
      get { return _snippets; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ECorpus")]
    public enum ECorpus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSAL", Value=0)]
      UNIVERSAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEB", Value=1)]
      WEB = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IMAGES", Value=2)]
      IMAGES = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCAL", Value=3)]
      LOCAL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEWS", Value=4)]
      NEWS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRODUCTS", Value=5)]
      PRODUCTS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VIDEO", Value=6)]
      VIDEO = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}