// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: baseDef.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "baseDef.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PTBuf {

namespace {

const ::google::protobuf::EnumDescriptor* PBECurrencyType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_baseDef_2eproto() {
  protobuf_AddDesc_baseDef_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "baseDef.proto");
  GOOGLE_CHECK(file != NULL);
  PBECurrencyType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_baseDef_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_baseDef_2eproto() {
}

void protobuf_AddDesc_baseDef_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rbaseDef.proto\022\005PTBuf*k\n\017PBECurrencyTyp"
    "e\022\035\n\031PBE_CURRENCY_TYPE_INVALID\020\000\022\032\n\026PBE_"
    "CURRENCY_TYPE_COIN\020\001\022\035\n\031PBE_CURRENCY_TYP"
    "E_DIAMOND\020\002", 131);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "baseDef.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_baseDef_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_baseDef_2eproto {
  StaticDescriptorInitializer_baseDef_2eproto() {
    protobuf_AddDesc_baseDef_2eproto();
  }
} static_descriptor_initializer_baseDef_2eproto_;
const ::google::protobuf::EnumDescriptor* PBECurrencyType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBECurrencyType_descriptor_;
}
bool PBECurrencyType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PTBuf

// @@protoc_insertion_point(global_scope)
